# Generated by Django 5.1.2 on 2025-01-22 00:00

from django.db import migrations, models


def alter_slug_field(apps, schema_editor):
    """Alter the slug field to allow 200 characters"""
    # This migration uses PostgreSQL-specific raw SQL (ALTER COLUMN ... TYPE,
    # DO $$ blocks, JSONB). Skip on other backends (e.g. SQLite) where the
    # schema is created directly from the model definitions.
    if schema_editor.connection.vendor != 'postgresql':
        return
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Get the actual table name from Django's model
        Lesson = apps.get_model('myApp', 'Lesson')
        table_name = Lesson._meta.db_table
        
        # Alter the slug column
        cursor.execute(
            f'ALTER TABLE {schema_editor.quote_name(table_name)} ALTER COLUMN slug TYPE varchar(200);'
        )
        
        # Add content column if it doesn't exist
        cursor.execute(f"""
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='{table_name}' AND column_name='content'
                ) THEN
                    ALTER TABLE {schema_editor.quote_name(table_name)} 
                    ADD COLUMN content JSONB DEFAULT '{{}}'::jsonb;
                END IF;
            END $$;
        """)


def reverse_alter_slug_field(apps, schema_editor):
    """Reverse: change slug back to 50 characters"""
    if schema_editor.connection.vendor != 'postgresql':
        return
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        Lesson = apps.get_model('myApp', 'Lesson')
        table_name = Lesson._meta.db_table
        cursor.execute(
            f'ALTER TABLE {schema_editor.quote_name(table_name)} ALTER COLUMN slug TYPE varchar(50);'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_lesson_content'),
    ]

    operations = [
        migrations.RunPython(alter_slug_field, reverse_alter_slug_field),
    ]

