# Generated by Django 4.2.29 on 2026-04-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_tenant_referrals'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='myApp_aiusa_tenant__dee2b5_idx',
            old_name='myApp_aiusa_tenant__8ff736_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='myApp_aiusa_course__9e50eb_idx',
            old_name='myApp_aiusa_course__ef1057_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='myApp_aiusa_feature_15a2df_idx',
            old_name='myApp_aiusa_feature_3f79a1_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantdomain',
            new_name='myApp_tenan_tenant__a2e38b_idx',
            old_name='myApp_tenan_tenant__ff596f_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantmembership',
            new_name='myApp_tenan_tenant__799b0e_idx',
            old_name='myApp_tenan_tenant__2ce5ff_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantmembership',
            new_name='myApp_tenan_user_id_fd02ed_idx',
            old_name='myApp_tenan_user_id_3be96a_idx',
        ),
    ]
