# Generated by Django 5.1.2 on 2026-05-25 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0035_add_lesson_ai_image_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('setup_fee_cents', models.PositiveIntegerField()),
                ('monthly_cents', models.PositiveIntegerField()),
                ('yearly_cents', models.PositiveIntegerField()),
                ('stripe_product_id', models.CharField(blank=True, max_length=100)),
                ('stripe_price_setup_id', models.CharField(blank=True, max_length=100)),
                ('stripe_price_monthly_id', models.CharField(blank=True, max_length=100)),
                ('stripe_price_yearly_id', models.CharField(blank=True, max_length=100)),
                ('stripe_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TenantNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Supports HTML')),
                ('cta_type', models.CharField(choices=[('none', 'No CTA'), ('upgrade', 'Upgrade to tier'), ('url', 'Custom URL')], default='none', max_length=20)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('cta_billing_interval', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('cta_custom_url', models.URLField(blank=True)),
                ('send_email', models.BooleanField(default=True)),
                ('show_modal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-notification__created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='studentiplog',
            new_name='myApp_stude_tenant__cacc28_idx',
            old_name='myApp_stude_tenant__4a6412_idx',
        ),
        migrations.RenameIndex(
            model_name='studentiplog',
            new_name='myApp_stude_tenant__a13b31_idx',
            old_name='myApp_stude_tenant__2cdb38_idx',
        ),
        migrations.RenameIndex(
            model_name='studentiplog',
            new_name='myApp_stude_tenant__c8337f_idx',
            old_name='myApp_stude_tenant__f71547_idx',
        ),
        migrations.RenameIndex(
            model_name='studentiplog',
            new_name='myApp_stude_tenant__714d17_idx',
            old_name='myApp_stude_tenant__7cfd4f_idx',
        ),
        migrations.AddField(
            model_name='tenantnotification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantnotification',
            name='cta_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='myApp.pricingtier'),
        ),
        migrations.AddField(
            model_name='tenantnotificationdelivery',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='myApp.tenantnotification'),
        ),
        migrations.AddField(
            model_name='tenantnotificationdelivery',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='myApp.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantnotificationdelivery',
            unique_together={('notification', 'tenant')},
        ),
    ]
