# Generated by Django 5.1.2 on 2026-05-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0037_seed_pricing_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingtier',
            name='charge_setup_fee',
            field=models.BooleanField(default=True, help_text='If False, setup fee is skipped at checkout for this tier.'),
        ),
    ]
