# Generated by Django 5.1.2 on 2026-05-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0038_pricing_tier_charge_setup_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='setup_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenantnotification',
            name='cta_type',
            field=models.CharField(choices=[('none', 'No CTA'), ('upgrade', 'Upgrade to tier'), ('setup_fee', 'Pay setup fee'), ('url', 'Custom URL')], default='none', max_length=20),
        ),
    ]
