# Generated by Django 5.1.2 on 2026-05-26 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0039_tenant_setup_fee_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='theme_preference',
            field=models.CharField(blank=True, choices=[('', 'Use tenant default'), ('dark', 'Dark'), ('light', 'Light')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_categories', to='myApp.tenant')),
            ],
            options={
                'verbose_name_plural': 'forum categories',
                'ordering': ['order', 'name'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='forum_images/')),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='myApp.forumcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='myApp.tenant')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='myApp.forumcomment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to='myApp.tenant')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myApp.forumpost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('celebrate', 'Celebrate'), ('support', 'Support'), ('insightful', 'Insightful')], default='like', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='myApp.forumcomment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='myApp.forumpost')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reactions', to='myApp.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['tenant', '-created_at'], name='myApp_forum_tenant__ea6aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['tenant', 'author'], name='myApp_forum_tenant__3bf29c_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['tenant', 'category'], name='myApp_forum_tenant__eaf686_idx'),
        ),
        migrations.AddIndex(
            model_name='forumcomment',
            index=models.Index(fields=['post', 'created_at'], name='myApp_forum_post_id_b37fac_idx'),
        ),
        migrations.AddIndex(
            model_name='forumreaction',
            index=models.Index(fields=['post', 'reaction_type'], name='myApp_forum_post_id_a8502c_idx'),
        ),
        migrations.AddIndex(
            model_name='forumreaction',
            index=models.Index(fields=['comment', 'reaction_type'], name='myApp_forum_comment_f1aab1_idx'),
        ),
        migrations.AddConstraint(
            model_name='forumreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('tenant', 'user', 'post', 'reaction_type'), name='uniq_forum_reaction_post'),
        ),
        migrations.AddConstraint(
            model_name='forumreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('tenant', 'user', 'comment', 'reaction_type'), name='uniq_forum_reaction_comment'),
        ),
    ]
