# Generated by Django 5.1.2 on 2026-06-05 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0040_theme_preference_and_forum_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='category_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_categories', to='myApp.tenant')),
            ],
            options={
                'verbose_name': 'Course category',
                'verbose_name_plural': 'Course categories',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_course_category_tenant_name')],
            },
        ),
    ]
