# Generated by Django 5.1.2 on 2026-06-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0043_event_eventregistration_event_uniq_event_tenant_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonquiz',
            name='is_required',
            field=models.BooleanField(default=False, help_text='If true, quiz must be passed to complete the lesson. Defaults to optional so quizzes never block progression unless an admin opts in.'),
        ),
    ]
