# Generated by Django 5.1.2 on 2026-06-23 13:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0044_alter_lessonquiz_is_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ghl_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GHLConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghl_location_id', models.CharField(max_length=128, unique=True)),
                ('ghl_company_id', models.CharField(blank=True, default='', max_length=128)),
                ('access_token_encrypted', models.TextField(blank=True, default='')),
                ('refresh_token_encrypted', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, default='')),
                ('sync_status', models.CharField(choices=[('connected', 'Connected'), ('error', 'Error'), ('revoked', 'Revoked')], default='connected', max_length=20)),
                ('status_detail', models.CharField(blank=True, default='', max_length=255)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ghl_connection', to='myApp.tenant')),
            ],
            options={
                'verbose_name': 'GHL Connection',
                'verbose_name_plural': 'GHL Connections',
            },
        ),
        migrations.CreateModel(
            name='GHLLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghl_contact_id', models.CharField(max_length=128)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_hash', models.CharField(blank=True, default='', max_length=64)),
                ('sync_status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('unmatched', 'Unmatched')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='myApp.ghlconnection')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ghl_links', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ghl_links', to='myApp.tenant')),
            ],
            options={
                'verbose_name': 'GHL Link',
                'verbose_name_plural': 'GHL Links',
            },
        ),
        migrations.AddIndex(
            model_name='ghlconnection',
            index=models.Index(fields=['sync_status'], name='myApp_ghlco_sync_st_77a1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='ghlconnection',
            index=models.Index(fields=['token_expires_at'], name='myApp_ghlco_token_e_72f3cb_idx'),
        ),
        migrations.AddIndex(
            model_name='ghllink',
            index=models.Index(fields=['tenant', 'student'], name='myApp_ghlli_tenant__c06fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='ghllink',
            index=models.Index(fields=['tenant', 'sync_status'], name='myApp_ghlli_tenant__5bce1b_idx'),
        ),
        migrations.AddConstraint(
            model_name='ghllink',
            constraint=models.UniqueConstraint(fields=('tenant', 'ghl_contact_id'), name='uniq_ghllink_tenant_contact'),
        ),
    ]
