# Generated by Django 5.1.2 on 2026-06-24 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0045_tenant_ghl_enabled_ghlconnection_ghllink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GhlEmbedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghl_location_id', models.CharField(blank=True, default='', max_length=128)),
                ('ghl_user_id', models.CharField(blank=True, default='', max_length=128)),
                ('ghl_email', models.CharField(blank=True, default='', max_length=255)),
                ('ghl_user_name', models.CharField(blank=True, default='', max_length=255)),
                ('ghl_role', models.CharField(blank=True, default='', max_length=64)),
                ('ghl_user_type', models.CharField(blank=True, default='', max_length=64)),
                ('impersonated_owner', models.BooleanField(default=False)),
                ('django_session_key', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.ghlconnection')),
                ('resolved_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ghl_embed_sessions', to='myApp.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='myApp_ghlem_tenant__bd41af_idx'), models.Index(fields=['ghl_location_id'], name='myApp_ghlem_ghl_loc_8dff83_idx')],
            },
        ),
    ]
