# Generated by Django 5.1.2 on 2026-06-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0046_ghlembedsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ghl_calendar_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='event',
            name='ghl_event_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ghl', 'GHL')], default='manual', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'ghl')), fields=('tenant', 'ghl_event_id'), name='uniq_event_tenant_ghl_event'),
        ),
    ]
