# Generated by Django 5.1.2 on 2026-06-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0047_event_ghl_calendar_id_event_ghl_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlconnection',
            name='event_calendar_ids',
            field=models.TextField(blank=True, default=''),
        ),
    ]
