# Generated by Django 5.1.2 on 2026-07-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0048_ghlconnection_event_calendar_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio_duration_seconds',
            field=models.IntegerField(default=0, help_text='Duration of the narration MP3 in seconds'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio_error',
            field=models.TextField(blank=True, default='', help_text='Error message if audio generation fails'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', help_text='Status of AI audio narration generation', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio_url',
            field=models.URLField(blank=True, default='', help_text='Public URL of the AI-narrated MP3 for this lesson'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='feature',
            field=models.CharField(choices=[('course_structure', 'Course Structure'), ('lesson_metadata', 'Lesson Metadata'), ('lesson_content', 'Lesson Content'), ('lesson_image', 'Lesson Image'), ('lesson_audio', 'Lesson Audio'), ('lesson_quiz', 'Lesson Quiz'), ('course_exam', 'Course Exam')], max_length=40),
        ),
    ]
