# Generated by Django 5.1 on 2026-07-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0049_lesson_audio_duration_seconds_lesson_audio_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text='ISO 639-1/639-2 code, e.g. it, fil', max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('ai_clean_title', models.CharField(blank=True, default='', max_length=200)),
                ('ai_short_summary', models.TextField(blank=True, default='')),
                ('ai_full_description', models.TextField(blank=True, default='')),
                ('ai_outcomes', models.JSONField(blank=True, default=list)),
                ('ai_coach_actions', models.JSONField(blank=True, default=list)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Editor.js content blocks')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('audio_url', models.URLField(blank=True, default='')),
                ('audio_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='myApp.lesson')),
            ],
            options={
                'ordering': ['language_code'],
                'unique_together': {('lesson', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='LessonQuizTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='myApp.lessonquiz')),
            ],
            options={
                'ordering': ['language_code'],
                'unique_together': {('quiz', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='LessonQuizQuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('text', models.TextField(blank=True, default='')),
                ('option_a', models.CharField(blank=True, default='', max_length=300)),
                ('option_b', models.CharField(blank=True, default='', max_length=300)),
                ('option_c', models.CharField(blank=True, default='', max_length=300)),
                ('option_d', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='myApp.lessonquizquestion')),
            ],
            options={
                'ordering': ['language_code'],
                'unique_together': {('question', 'language_code')},
            },
        ),
    ]
