# Generated by Django 5.1 on 2026-07-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0050_lesson_translations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('short_description', models.CharField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('translation_source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='myApp.course')),
            ],
            options={'ordering': ['language_code'], 'unique_together': {('course', 'language_code')}},
        ),
        migrations.CreateModel(
            name='ModuleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('translation_source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='myApp.module')),
            ],
            options={'ordering': ['language_code'], 'unique_together': {('module', 'language_code')}},
        ),
        migrations.AddField(
            model_name='lessontranslation',
            name='translation_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='lessontranslation',
            name='audio_duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lessontranslation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonquizquestiontranslation',
            name='translation_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonquizquestiontranslation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonquiztranslation',
            name='translation_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonquiztranslation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
