# Generated by Django 5.1.2 on 2026-07-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0051_localization_expansion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='file_url',
            field=models.URLField(blank=True, help_text='Iceberg CDN URL or external link (Google Drive, etc.)', max_length=500),
        ),
    ]
