# Generated by Django 5.1.2 on 2026-08-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0057_student_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grants_membership_months',
            field=models.PositiveIntegerField(blank=True, help_text='If set, purchasing this course grants this many months of complimentary membership.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='included_in_membership',
            field=models.BooleanField(default=True, help_text='If off, an active membership does NOT unlock this course; it must be purchased separately.'),
        ),
        migrations.AddField(
            model_name='course',
            name='member_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price for active members. Blank means members pay the regular price.', max_digits=8, null=True),
        ),
    ]
