# Generated by Django 5.1.2 on 2026-08-22 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0060_membershipplan_past_due_grace_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='tiers_cumulative',
            field=models.BooleanField(default=True, help_text='When multiple membership tiers exist, a higher tier also unlocks every lower tier’s courses (Pro ⊇ Starter). Turn off to make each tier an independent, standalone course set.'),
        ),
        migrations.AddField(
            model_name='studentsubscription',
            name='access_mode',
            field=models.CharField(choices=[('all_access', 'All-access (whole catalog)'), ('tiered', 'Tiered (specific membership tier)')], default='all_access', help_text='all_access = whole catalog (legacy/comp); tiered = a specific MembershipTier.', max_length=20),
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Short identifier, unique per tenant (e.g. "starter").', max_length=60)),
                ('name', models.CharField(default='Membership', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Student-facing pitch for this tier')),
                ('rank', models.PositiveIntegerField(default=0, help_text='Ordering weight; higher = more inclusive (Pro > Starter).')),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly price in USD. Blank disables monthly billing for this tier.', max_digits=8, null=True)),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Yearly price in USD. Blank disables yearly billing for this tier.', max_digits=8, null=True)),
                ('includes_all', models.BooleanField(default=False, help_text='All-access tier: unlocks the entire catalog.')),
                ('is_purchasable', models.BooleanField(default=True, help_text='Whether NEW checkouts can select this tier. Turning it off stops new signups but never revokes access for current subscribers.')),
                ('is_archived', models.BooleanField(default=False, help_text='Soft-deleted: hidden from admin/checkout but retained for reporting and existing subscribers.')),
                ('stripe_product_id', models.CharField(blank=True, default='', max_length=120)),
                ('stripe_monthly_price_id', models.CharField(blank=True, default='', max_length=120)),
                ('stripe_yearly_price_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, help_text='Courses this tier unlocks (before cumulative lower-tier inclusion).', related_name='membership_tiers', to='myApp.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_tiers', to='myApp.tenant')),
            ],
            options={
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='grants_membership_tier',
            field=models.ForeignKey(blank=True, help_text='Tier the complimentary grant targets. Blank grants all-access (whole catalog).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_granting_courses', to='myApp.membershiptier'),
        ),
        migrations.AddField(
            model_name='studentsubscription',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='The membership tier held (only when access_mode=tiered).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='myApp.membershiptier'),
        ),
        migrations.AddConstraint(
            model_name='studentsubscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('access_mode', 'tiered'), ('tier__isnull', False)), models.Q(('access_mode', 'all_access'), ('tier__isnull', True)), _connector='OR'), name='studentsub_tier_matches_access_mode'),
        ),
        migrations.AddIndex(
            model_name='membershiptier',
            index=models.Index(fields=['tenant', 'is_archived', 'is_purchasable'], name='myApp_membe_tenant__e931b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membershiptier',
            unique_together={('tenant', 'code'), ('tenant', 'rank')},
        ),
    ]
