# Generated by Django 5.1.2 on 2026-08-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0061_membershipplan_tiers_cumulative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='comp_grant_reset',
            field=models.BooleanField(default=False, help_text='How a new complimentary grant combines with remaining time. On = reset to N months from the latest purchase. Off = extend/stack N months onto whatever time is left.'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='member_pricing_requires_annual',
            field=models.BooleanField(default=False, help_text='If on, only annual and complimentary members get member pricing on courses; monthly members pay the standard price. Prevents "pay one month, grab the discount, cancel." Off = any active member gets it.'),
        ),
    ]
