# Generated by Django 5.1.2 on 2026-09-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0069_lesson_what_youll_learn_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='ai_hero_image_url',
            field=models.URLField(blank=True, default='', help_text='Iceberg CDN URL of the AI-generated hero image for this lesson'),
        ),
        migrations.AlterField(
            model_name='lessontranslation',
            name='language_code',
            field=models.CharField(help_text='ISO 639-1/639-2 code, e.g. it, fil, es', max_length=10),
        ),
    ]
