# Generated by Django 5.1.2 on 2026-09-04 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0070_alter_lesson_ai_hero_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='library_category_thumbnails/')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_categories', to='myApp.tenant')),
            ],
            options={
                'verbose_name': 'Library category',
                'verbose_name_plural': 'Library categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('recording', 'Webinar recording'), ('lecture', 'Short lecture'), ('document', 'Document'), ('tool', 'Tool')], default='document', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='library_item_thumbnails/')),
                ('file_url', models.URLField(blank=True, help_text='Iceberg CDN URL or external link for documents and tools.', max_length=500)),
                ('video_url', models.URLField(blank=True, help_text='Iceberg file, Vimeo, YouTube, or Drive URL for recordings and lectures.', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_items', to='myApp.librarycategory')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='myApp.tenant')),
            ],
            options={
                'verbose_name': 'Library item',
                'verbose_name_plural': 'Library items',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='librarycategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_library_category_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='libraryitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_library_item_tenant_slug'),
        ),
    ]
