# Generated by Django 5.1.2 on 2026-09-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0071_library_category_libraryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycategory',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Iceberg CDN URL for the category thumbnail.', max_length=500),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Iceberg CDN URL for the item thumbnail.', max_length=500),
        ),
    ]
